create pkg

diff --git a/usr/sbin/overlayroot-chroot b/usr/sbin/overlayroot-chroot
--- a/usr/sbin/overlayroot-chroot
+++ b/usr/sbin/overlayroot-chroot
@@ -22,72 +22,76 @@ set -f # disable path expansion
 REMOUNTS=""
 
 error() {
-	printf "ERROR: $@\n" 1>&2
+    printf "ERROR: %s\n" "$*" 1>&2
 }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
 
 info() {
-	printf "INFO: $@\n" 1>&2
+    printf "INFO: %s\n" "$*" 1>&2
 }
 
+# shellcheck disable=SC3043
 get_lowerdir() {
-	local overlay=""
-	overlay=$(awk \
-		'$1 == "overlayroot" && $2 == "/" { print $0 }' /proc/mounts)
-	if [ -n "${overlay}" ]; then
-		lowerdir=${overlay##*lowerdir=}
-		lowerdir=${lowerdir%%,*}
-		if mountpoint "${lowerdir}" >/dev/null; then
-			_RET="${lowerdir}"
-		else
-			fail "Unable to find the overlayroot lowerdir"
-		fi
-	else
-		fail "Unable to find an overlayroot filesystem"
-	fi
+    local overlay=""
+    local lowerdir=""
+    overlay=$(awk \
+        '$1 == "overlayroot" && $2 == "/" { print $0 }' /proc/mounts)
+    if [ -n "${overlay}" ]; then
+        lowerdir=${overlay##*lowerdir=}
+        lowerdir=${lowerdir%%,*}
+        if mountpoint "${lowerdir}" >/dev/null; then
+            _RET="${lowerdir}"
+        else
+            fail "Unable to find the overlayroot lowerdir"
+        fi
+    else
+        fail "Unable to find an overlayroot filesystem"
+    fi
 }
 
+# shellcheck disable=SC3043
 clean_exit() {
-	local mounts="$1" rc=0 d="" lowerdir="" mp=""
-	for d in ${mounts}; do
-		if mountpoint ${d} >/dev/null; then
-			umount ${d} || rc=1
-		fi
-	done
-	for mp in $REMOUNTS; do
-		mount -o remount,ro "${mp}" ||
-			error "Note that [${mp}] is still mounted read/write"
-	done
-	[ "$2" = "return" ] && return ${rc} || exit ${rc}
+    local mounts="$1" rc=0 d="" lowerdir="" mp=""
+    # shellcheck disable=SC2086
+    for d in ${mounts}; do
+        if mountpoint "${d}" >/dev/null; then
+            umount "${d}" || rc=1
+        fi
+    done
+    # shellcheck disable=SC2086
+    for mp in $REMOUNTS; do
+        mount -o remount,ro "${mp}" ||
+            error "Note that [${mp}] is still mounted read/write"
+    done
+    [ "$2" = "return" ] && return ${rc} || exit ${rc}
 }
 
-# Try to find the overlayroot filesystem
 get_lowerdir
 lowerdir=${_RET}
 
+# shellcheck disable=SC2086
 recurse_mps=$(awk '$1 ~ /^\/dev\// && $2 ~ starts { print $2 }' \
-	starts="^$lowerdir/" /proc/mounts)
+    starts="^$lowerdir/" /proc/mounts)
 
 mounts=
 for d in proc run sys; do
-	if ! mountpoint "${lowerdir}/${d}" >/dev/null; then
-		mount -o bind "/${d}" "${lowerdir}/${d}" || fail "Unable to bind /${d}"
-		mounts="$mounts $lowerdir/$d"
-		trap "clean_exit \"${mounts}\" || true" EXIT HUP INT QUIT TERM
-	fi
+    if ! mountpoint "${lowerdir}/${d}" >/dev/null; then
+        mount -o bind "/${d}" "${lowerdir}/${d}" || fail "Unable to bind /${d}"
+        mounts="$mounts $lowerdir/$d"
+        trap 'clean_exit "${mounts}" || true' EXIT HUP INT QUIT TERM
+    fi
 done
 
-# Remount with read/write
+# shellcheck disable=SC2086
 for mp in "$lowerdir" $recurse_mps; do
-	mount -o remount,rw "${mp}" &&
-		REMOUNTS="$mp $REMOUNTS" ||
-		fail "Unable to remount [$mp] writable"
+    mount -o remount,rw "${mp}" &&
+        REMOUNTS="$mp $REMOUNTS" ||
+        fail "Unable to remount [$mp] writable"
 done
 info "Chrooting into [${lowerdir}]"
-chroot ${lowerdir} "$@"
+
+chroot "${lowerdir}" "$@"
 
 # Clean up mounts on exit
 clean_exit "${mounts}" "return"
 trap "" EXIT HUP INT QUIT TERM
-
-# vi: ts=4 noexpandtab
